Repository TheRealJackiBoi/BlogExamProject, pull requests merged in 2023-12, with the labels that each got.

#13 Index frontpage
  src/App.jsx
  src/assets/logo/logo.svg
  src/pages/Index.jsx
Labels: good first issue

#16 Styling index
  src/pages/Index.jsx
Labels: enhancement

#28 Readme
  README.md
  src/assets/logo.svg
  src/assets/logo/logo.svg
  src/pages/Index.jsx
Labels: documentation

#45 New post modal
  src/api/services/posts.js
  src/components/navbar/NavBar.jsx
  src/pages/Index.jsx
  src/pages/MainLayout.jsx
  src/pages/NewPost.jsx
Labels: enhancement

#48 Readme
  README.md
Labels: documentation

#54 fixed signup
  src/api/services/auth/auth.js
  src/components/navbar/NavBar.jsx
  src/pages/auth/SignUp.jsx
Labels: enhancement

#67 V1.0
  .eslintrc.cjs
  .github/workflows/ci.yml
  .gitignore
  Dockerfile
  README.md
  nginx.conf
  package-lock.json
  package.json
  src/App.jsx
  src/api/services/auth/auth.js
  src/api/services/config.js
  src/api/services/posts.js
  src/api/services/supabase/image-facade.js
  src/api/services/supabase/supabase.js
  src/assets/logo.svg
  src/components/navbar/NavBar.jsx
  src/components/post/Edit.jsx
  src/components/post/Like.jsx
  src/components/post/Post.jsx
  src/components/post/Username.jsx
  src/main.jsx
  src/pages/ErrorPage.jsx
  src/pages/Home.jsx
  src/pages/Index.jsx
  src/pages/MainLayout.jsx
  src/pages/MyPosts.jsx
  src/pages/NewPost.jsx
  src/pages/PostEdit.jsx
  src/pages/UserPosts.jsx
  src/pages/UserSettings.jsx
  src/pages/auth/Login.jsx
  src/pages/auth/SignUp.jsx
  tailwind.config.js
  utilities/img/frontEndMap1.png
  utilities/img/frontEndMap2.png
  utilities/img/frontEndMap3.png
Labels: V1.0
